service: vrc-video-api

plugins:
  - serverless-python-requirements

custom:
  s3_bucket: ${env:S3_PUBLIC_BUCKET}
  yt_api_key: ${env:API_KEY}
  contents_bucket: ${self:service}-${opt:stage}-bucket
  vrc_video_table: ${self:service}-${opt:stage}-table
  pythonRequirements:
    dockerizePip: true
    dockerImage: lambci/lambda:build-python3.7
    useStaticCache: false
    useDownloadCache: false
    layer: true
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}
  cf_dmain:
    Fn::Join:
      - ""
      - - "https://"
        - Fn::GetAtt:
            - ContentsCloudFront
            - DomainName

provider:
  name: aws
  runtime: python3.7
  provider: ${opt:stage}
  lambdaHashingVersion: 20201221
  region: ap-northeast-1
  role: ${env:LAMBDA_IAM}
  timeout: 30
  logRetentionInDays: 14
  tracing:
    apiGateway: true
    lambda: true

package:
  individually: true
  exclude:
    - node_modules/**
    - doc/**
    - .gitignore
    - package-lock.json
    - requirements.txt
    - serverless.yml
    - .env
    - memo.txt
    - example.py
    - src/**
    - html/**
    # NOTE: ./addonにyt-dlpが必要
    - addon/**
layers:
  utilsLayer:
    path: src/layers/utils
    name: ${opt:stage}-${self:service}-utilsLayer
    description: utils
    compatibleRuntimes:
      - python3.7
  # NOTE: ./src/layers/chromeにchromedriverとheadless-chromiumが必要
  # NOTE: バージョンは厳密なんだけど何入れて動いたかマジで忘れた
  chromeLayer:
    path: src/layers/chrome
    name: ${opt:stage}-${self:service}-chromeLayer
    description: chrome
    compatibleRuntimes:
      - python3.7

functions:
  # 登録
  post_yt_channel_regist:
    handler: src/lambda/post_yt_channel_regist/handler.main
    package:
      include:
        - src/lambda/post_yt_channel_regist/handler.py
    environment:
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /video/yt/channel/regist
          method: post
          cors: true
  # 動画取得
  get_yt_channel:
    handler: src/lambda/get_yt_channel/handler.main
    package:
      include:
        - src/lambda/get_yt_channel/handler.py
        - addon/yt-dlp
    environment:
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
      API_KEY: ${self:custom.yt_api_key}
      CF_DOMAIN: ${self:custom.cf_dmain}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          # ?n=n
          path: /videos/yt/ch/{channel_id}
          method: get
          cors: true
      - http:
          path: /videos/yt/ch/{channel_id}
          method: head
          cors: true
  # リスト取得
  get_yt_channel_list:
    handler: src/lambda/get_yt_channel_list/handler.main
    timeout: 30
    package:
      include:
        - src/lambda/get_yt_channel_list/handler.py
    environment:
      S3_PUBLIC_BUCKET: ${self:custom.s3_bucket}
      API_KEY: ${self:custom.yt_api_key}
      CF_DOMAIN:
        Fn::Join:
          - ""
          - - "https://"
            - Fn::GetAtt:
                - ContentsCloudFront
                - DomainName
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /videos/yt/chlist/{channel_id}
          method: head
          cors: true
      - http:
          path: /videos/yt/chlist/{channel_id}
          method: get
          cors: true
  batch_tver_video_update:
    handler: src/lambda/batch_tver_video_update/handler.main
    timeout: 300
    package:
      include:
        - src/lambda/batch_tver_video_update/handler.py
    environment:
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
    events:
      - schedule: cron(30 2 * * ? *)
      - schedule: cron(30 18 * * ? *)
      - schedule: cron(30 10 * * ? *)
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-python38-beautifulsoup4:13
      - { Ref: PythonRequirementsLambdaLayer }
      - { Ref: ChromeLayerLambdaLayer }
  # batch_tver_lineup_update:
  #   handler: src/lambda/batch_tver_lineup_update/handler.main
  #   timeout: 300
  #   package:
  #     include:
  #       - src/lambda/batch_tver_lineup_update/handler.py
  #   environment:
  #     VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
  #   events:
  #     - schedule: cron(0 12 1 * ? *)
  #   layers:
  #     - { Ref: UtilsLayerLambdaLayer }
  #     - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-python38-beautifulsoup4:13
  get_tver_channel:
    handler: src/lambda/get_tver_channel/handler.main
    package:
      include:
        - src/lambda/get_tver_channel/handler.py
    environment:
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
      CF_DOMAIN:
        Fn::Join:
          - ""
          - - "https://"
            - Fn::GetAtt:
                - ContentsCloudFront
                - DomainName
    layers:
      - { Ref: UtilsLayerLambdaLayer }
    events:
      - http:
          # ?n=n
          path: /videos/tver/{attribute}
          method: get
          cors: true
      - http:
          path: /videos/tver/{attribute}
          method: head
          cors: true
  # get_tver_search_lineup:
  #   handler: src/lambda/get_tver_search_lineup/handler.main
  #   package:
  #     include:
  #       - src/lambda/get_tver_search_lineup/handler.py
  #   environment:
  #     VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
  #     CF_DOMAIN:
  #       Fn::Join:
  #         - ""
  #         - - "https://"
  #           - Fn::GetAtt:
  #               - ContentsCloudFront
  #               - DomainName
  #   layers:
  #     - { Ref: UtilsLayerLambdaLayer }
  #     - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-python38-beautifulsoup4:13
  #   events:
  #     - http:
  #         path: /videos/tv/lp
  #         method: get
  #         cors: true
  #     - http:
  #         path: /videos/tv/lp
  #         method: head
  #         cors: true
  get_ytlive_channel:
    handler: src/lambda/get_ytlive_channel/handler.main
    package:
      include:
        - src/lambda/get_ytlive_channel/handler.py
    environment:
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
      API_KEY: ${self:custom.yt_api_key}
      CF_DOMAIN:
        Fn::Join:
          - ""
          - - "https://"
            - Fn::GetAtt:
                - ContentsCloudFront
                - DomainName
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /videos/ytlive/ch/{channel_id}
          method: get
          cors: true
      - http:
          path: /videos/ytlive/ch/{channel_id}
          method: head
          cors: true
  get_yt_query:
    handler: src/lambda/get_yt_query/handler.main
    package:
      include:
        - src/lambda/get_yt_query/handler.py
        - addon/yt-dlp
    environment:
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
      API_KEY: ${self:custom.yt_api_key}
      CF_DOMAIN:
        Fn::Join:
          - ""
          - - "https://"
            - Fn::GetAtt:
                - ContentsCloudFront
                - DomainName
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /videos/yt/query
          method: get
          cors: true
      - http:
          path: /videos/yt/query
          method: head
          cors: true
  # リスト取得
  get_yt_query_list:
    handler: src/lambda/get_yt_query_list/handler.main
    timeout: 30
    package:
      include:
        - src/lambda/get_yt_query_list/handler.py
    environment:
      S3_PUBLIC_BUCKET: ${self:custom.s3_bucket}
      API_KEY: ${self:custom.yt_api_key}
      CF_DOMAIN:
        Fn::Join:
          - ""
          - - "https://"
            - Fn::GetAtt:
                - ContentsCloudFront
                - DomainName
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /videos/yt/query/list
          method: head
          cors: true
      - http:
          path: /videos/yt/query/list
          method: get
          cors: true
  get_yt_ch_all:
    handler: src/lambda/get_yt_ch_all/handler.main
    timeout: 30
    package:
      include:
        - src/lambda/get_yt_ch_all/handler.py
    environment:
      API_KEY: ${self:custom.yt_api_key}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /api/yt/ch/{channel_id}/video/all
          method: get
          cors: true
  get_yt_ch_continuous_play:
    handler: src/lambda/get_yt_ch_continuous_play/handler.main
    package:
      include:
        - src/lambda/get_yt_ch_continuous_play/handler.py
        - addon/yt-dlp
    environment:
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
      API_KEY: ${self:custom.yt_api_key}
      CF_DOMAIN: ${self:custom.cf_dmain}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /yt/ch/{channel_id}/continuous
          method: get
          cors: true
  get_yt_pl_continuous_play:
    handler: src/lambda/get_yt_pl_continuous_play/handler.main
    package:
      include:
        - src/lambda/get_yt_pl_continuous_play/handler.py
        - addon/yt-dlp
    environment:
      VRC_VIDEO_TABLE: ${self:custom.vrc_video_table}
      API_KEY: ${self:custom.yt_api_key}
      CF_DOMAIN: ${self:custom.cf_dmain}
    layers:
      - { Ref: UtilsLayerLambdaLayer }
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          path: /yt/pl/{playlist_id}/continuous
          method: get
          cors: true
resources:
  Resources:
    vrcVideoTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:custom.vrc_video_table}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: video_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: video_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 2
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: True
    # 動画設置用S3
    ContentsS3:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        AccessControl: Private
        BucketName: ${self:custom.contents_bucket}
    # ナゲットポリシー
    ContentsS3Policy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: ContentsS3
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  Fn::Join:
                    - " "
                    - - "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity"
                      - Ref: StaticCloudFrontOriginAccessIdentity
              Action: s3:GetObject
              Resource:
                Fn::Join:
                  - "/"
                  - - Fn::GetAtt:
                        - ContentsS3
                        - Arn
                    - "*"
    # CDNのやつ
    ContentsCloudFront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: "Delivery static contents"
          DefaultRootObject: index.html
          HttpVersion: http2
          PriceClass: PriceClass_200 # 日本が含まってるやつ
          CustomErrorResponses:
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /error.mp4
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /error.mp4
          Origins:
            - Id: S3Origin
              DomainName:
                Fn::GetAtt:
                  - ContentsS3
                  - DomainName
              S3OriginConfig:
                OriginAccessIdentity:
                  Fn::Join:
                    - "/"
                    - - origin-access-identity/cloudfront
                      - Ref: StaticCloudFrontOriginAccessIdentity
          DefaultCacheBehavior:
            AllowedMethods:
              - HEAD
              - GET
            CachedMethods:
              - HEAD
              - GET
            Compress: false
            DefaultTTL: 900
            MaxTTL: 900
            MinTTL: 900
            ForwardedValues:
              QueryString: false
            SmoothStreaming: false
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: https-only
    # OAI
    StaticCloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment:
            Ref: AWS::StackName
  Outputs:
    ContentsCloudFrontUrl:
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Fn::GetAtt:
                - ContentsCloudFront
                - DomainName
